name: Publish Github-Pages

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Install Python and pipenv
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: make install

    - name: Checkout target branch for publication
      shell: bash
      run: git fetch --depth=1 origin master

    - name: Publish
      run: |
        pipenv run pip install ghp-import
        pipenv run make github
      env:
        RELATIVE: 1
        GITHUB_TOKEN: ${{ secrets. GITHUB_BOT_TOKEN }}


